### ISSUE TITLE
Problem with server-checker

### ISSUE THREAD

**Issue by UnioDex** [jamezrin/PlayerBalancer#4]
I don't want people to join to specific motds. For this reason i set it up like that:
```marker-descs=[
      "(?i).*BAŞLADI*",
	  "(?i).*ÖLÜM OYUNU*",
	  "(?i).*YENİLENİYOR*",
	  "(?i).*BAŞLADI*"
    ]
```

If players quit a match from these motds and tries to join same group again he still join to ingame server. After 2-3 tries it joins to empty match.

**Comment by jamezrin** [comment]
Hello, paste your config so I can have a look. Probably the regex isn't working properly, you can enable debug-info to see in-depth info about it.

**Comment by UnioDex** [comment]
Here full config:
https://pastebin.com/JksWWXAY

I don't think regex has problem because it works for first join players. It happens to the players that joined a match and then quit and then join again. And the worst part is it is not happening all the time. So reproducing it is hard.

**Comment by jamezrin** [comment]
Please set debug-info to true and try reproducing it again. Once it happens send the messages the plugin prints to the console.

**Comment by jamezrin** [comment]
Of course it has an interval, the plugin relies on that interval.
Decreasing the interval down to 1000 will make BungeeCord ping every single one of your server every second. I haven't tested it myself but I don't think it will do much harm, just play with it. Also try decreasing the timeout otherwise some threads are going to be waiting there more time than needed, and the decreased interval with long timeout waits are able to cause problems.

**Comment by UnioDex** [comment]
```    # The interval between every round of checks (in milliseconds)
    interval=2500

    # The timeout of a ping, only applied to the CUSTOM tactic
    timeout=2000
```

Changed it like that. I will monitor for a while and report here if any problem happens.
